table DimListingAmenities
	lineageTag: eeadea57-d97d-43c6-b515-f5897e1a703d

	column 'Listing ID'
		dataType: int64
		formatString: 0
		lineageTag: 80fcfef5-ae09-43de-bbe0-660cf8cfe5de
		summarizeBy: none
		sourceColumn: Listing ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Amenity
		dataType: string
		lineageTag: ea00ca5a-bb2e-4f61-882e-9da0c5da3edd
		summarizeBy: none
		sourceColumn: Amenity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Amenity ID'
		dataType: int64
		isKey
		isNullable: false
		formatString: 0
		lineageTag: 37111358-9104-43c5-9fe9-6b96cf0bb458
		summarizeBy: none
		sourceColumn: Amenity ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition DimListingAmenities = m
		mode: import
		source =
				let
				    Quelle = Sql.Database("DESKTOP-Q1CNOQD\SQLEXPRESS", "Greek_Airbnb"),
				    dbo_DimListings = Quelle{[Schema="dbo",Item="DimListings"]}[Data],
				    #"Geänderter Typ" = Table.TransformColumnTypes(dbo_DimListings,{{"accommodates", Int64.Type}}),
				    #"Umbenannte Spalten" = Table.RenameColumns(#"Geänderter Typ",{{"listing_url", "listing_page_url"}, {"picture_url", "listing_image_url"}, {"name", "listing_name"}, {"description", "listing_description"}, {"accommodates", "accommodates_guests"}, {"bathrooms_text", "bathrooms_text"}, {"amenities", "amenities_list"}, {"price", "listing_price"}, {"has_availability", "has_availability_flag"}, {"instant_bookable", "instant_bookable_flag"}, {"minimum_nights", "min_nights_allowed"}, {"maximum_nights", "max_nights_allowed"}}),
				    #"Spalte nach Trennzeichen teilen" = Table.SplitColumn(#"Umbenannte Spalten", "bathrooms_text", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"bathrooms_text.1", "bathrooms_text.2"}),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Spalte nach Trennzeichen teilen",{{"bathrooms_text.1", Int64.Type}, {"bathrooms_text.2", type text}}),
				    #"Entfernte Spalten" = Table.RemoveColumns(#"Geänderter Typ1",{"bathrooms_text.2"}),
				    #"Umbenannte Spalten1" = Table.RenameColumns(#"Entfernte Spalten",{{"bathrooms_text.1", "bathrooms"}, {"min_nights_allowed", "minimum_nights"}, {"max_nights_allowed", "maximum_nights"}}),
				    #"Hinzugefügte benutzerdefinierte Spalte" = Table.AddColumn(#"Umbenannte Spalten1", "Min Profit", each [listing_price]*[minimum_nights]),
				    #"Geänderter Typ2" = Table.TransformColumnTypes(#"Hinzugefügte benutzerdefinierte Spalte",{{"Min Profit", Int64.Type}}),
				    #"Hinzugefügte benutzerdefinierte Spalte1" = Table.AddColumn(#"Geänderter Typ2", "Max Profit", each [listing_price]*[maximum_nights]),
				    #"Geänderter Typ3" = Table.TransformColumnTypes(#"Hinzugefügte benutzerdefinierte Spalte1",{{"Max Profit", Int64.Type}}),
				    #"Gefilterte Zeilen" = Table.SelectRows(#"Geänderter Typ3", each true),
				    #"Geänderter Typ4" = Table.TransformColumnTypes(#"Gefilterte Zeilen",{{"has_availability_flag", type text}}),
				    #"Ersetzter Wert" = Table.ReplaceValue(#"Geänderter Typ4","true","1",Replacer.ReplaceValue,{"has_availability_flag"}),
				    #"Ersetzter Wert1" = Table.ReplaceValue(#"Ersetzter Wert","false","0",Replacer.ReplaceValue,{"has_availability_flag"}),
				    #"Geänderter Typ5" = Table.TransformColumnTypes(#"Ersetzter Wert1",{{"has_availability_flag", Int64.Type}, {"instant_bookable_flag", type text}}),
				    #"Ersetzter Wert2" = Table.ReplaceValue(#"Geänderter Typ5","true","1",Replacer.ReplaceText,{"instant_bookable_flag"}),
				    #"Ersetzter Wert3" = Table.ReplaceValue(#"Ersetzter Wert2","false","0",Replacer.ReplaceText,{"instant_bookable_flag"}),
				    #"Geänderter Typ6" = Table.TransformColumnTypes(#"Ersetzter Wert3",{{"instant_bookable_flag", Int64.Type}}),
				    #"Andere entfernte Spalten" = Table.SelectColumns(#"Geänderter Typ6",{"listing_id", "amenities_list"}),
				    #"Analysierte JSON" = Table.TransformColumns(#"Andere entfernte Spalten",{{"amenities_list", Json.Document}}),
				    #"Erweiterte amenities_list" = Table.ExpandListColumn(#"Analysierte JSON", "amenities_list"),
				    #"Umbenannte Spalten2" = Table.RenameColumns(#"Erweiterte amenities_list",{{"amenities_list", "amenity"}}),
				    #"Gefilterte Zeilen1" = Table.SelectRows(#"Umbenannte Spalten2", each true),
				    #"Ersetzter Wert4" = Table.ReplaceValue(#"Gefilterte Zeilen1",".","",Replacer.ReplaceText,{"amenity"}),
				    #"Gefilterte Zeilen2" = Table.SelectRows(#"Ersetzter Wert4", each true),
				    #"Bereinigter Text" = Table.TransformColumns(#"Gefilterte Zeilen2",{{"amenity", Text.Clean, type text}}),
				    #"Text in Kleinbuchstaben" = Table.TransformColumns(#"Bereinigter Text",{{"amenity", Text.Lower, type text}}),
				    #"Hinzugefügter Index" = Table.AddIndexColumn(#"Text in Kleinbuchstaben", "Index", 1, 1, Int64.Type),
				    #"Neu angeordnete Spalten" = Table.ReorderColumns(#"Hinzugefügter Index",{"Index", "listing_id", "amenity"}),
				    #"Umbenannte Spalten3" = Table.RenameColumns(#"Neu angeordnete Spalten",{{"Index", "Amenity ID"}, {"listing_id", "Listing ID"}, {"amenity", "Amenity"}})
				in
				    #"Umbenannte Spalten3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

