table DimPropertyType
	lineageTag: eda18b8a-dd41-4e9e-8c18-1a7343562523

	column 'Property ID'
		dataType: int64
		isKey
		isNullable: false
		formatString: 0
		lineageTag: bceefd02-fe96-4775-89e7-73cfbff06ca1
		summarizeBy: none
		sourceColumn: Property ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Self selected property type. Hotels and Bed and Breakfasts are described as such by their hosts in this field
	column 'Property Type'
		dataType: string
		lineageTag: a68175b6-2846-4a48-a363-119d7cf65c7f
		summarizeBy: none
		sourceColumn: Property Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimPropertyType = m
		mode: import
		source =
				let
				    Quelle = Sql.Database("DESKTOP-Q1CNOQD\SQLEXPRESS", "Greek_Airbnb"),
				    dbo_DimPropertyType = Quelle{[Schema="dbo",Item="DimPropertyType"]}[Data],
				    #"Umbenannte Spalten" = Table.RenameColumns(dbo_DimPropertyType,{{"property_id", "Property ID"}, {"property_type", "Property Type"}})
				in
				    #"Umbenannte Spalten"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

