table FactReviews
	lineageTag: 628b8c36-1ad3-44f9-aa47-287220186071

	measure Running_Total_reviews =
			
			CALCULATE(
			    COUNT(FactReviews[Review ID]),
			    FILTER(
			        ALLSELECTED('Reviews Calendar Table'),
			        'Reviews Calendar Table'[Date] <=
			MAX('Reviews Calendar Table'[Date])
			    )
			)
		formatString: 0
		lineageTag: f683c32e-d24f-462b-96e3-7db76dfe2e96

		changedProperty = IsHidden

	/// The review id
	column 'Review ID'
		dataType: int64
		isKey
		isNullable: false
		formatString: 0
		lineageTag: d434ba81-3565-441f-84ba-aa0095f3c69b
		summarizeBy: none
		sourceColumn: Review ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	/// The listing id
	column 'Listing ID'
		dataType: int64
		formatString: 0
		lineageTag: 21517fe7-15ff-4fed-9b11-5271ee536173
		summarizeBy: none
		sourceColumn: Listing ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The reviewer’s id
	column 'Reviewer ID'
		dataType: int64
		formatString: 0
		lineageTag: 9413b7ba-f1f6-4d77-8d80-62a2f65819d1
		summarizeBy: none
		sourceColumn: Reviewer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// The review date
	column 'Review Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: c74ba376-def3-462c-97d1-115f3455ab7c
		summarizeBy: none
		sourceColumn: Review Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Reviewer’s comments
	column Comments
		dataType: string
		lineageTag: e45341b2-f715-4b04-be33-e1c5cdf91c35
		summarizeBy: none
		sourceColumn: Comments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Is Available Flag'
		dataType: string
		lineageTag: fc74a669-8640-4169-810c-cac4e5356e79
		summarizeBy: none
		sourceColumn: Is Available Flag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactReviews = m
		mode: import
		source =
				let
				    Quelle = Sql.Database("DESKTOP-Q1CNOQD\SQLEXPRESS", "Greek_Airbnb"),
				    dbo_FactReviews = Quelle{[Schema="dbo",Item="FactReviews"]}[Data],
				    #"Umbenannte Spalten" = Table.RenameColumns(dbo_FactReviews,{{"date", "Review Date"}, {"comments", "Comments"}, {"review_id", "Review ID"}, {"listing_id", "Listing ID"}, {"reviewer_id", "Reviewer ID"}}),
				    #"Zusammengeführte Abfragen" = Table.NestedJoin(#"Umbenannte Spalten", {"Listing ID", "Review Date"}, FactBookings, {"Listing ID", "Booking Date"}, "FactBookings", JoinKind.LeftOuter),
				    #"Erweiterte FactBookings" = Table.ExpandTableColumn(#"Zusammengeführte Abfragen", "FactBookings", {"Is Available Flag"}, {"Is Available Flag"})
				in
				    #"Erweiterte FactBookings"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

