table 'Host Calendar Table'
	lineageTag: 1cabffa7-9763-44c8-bb9d-6464dbeda645

	column Date
		dataType: dateTime
		isKey
		isNullable: false
		formatString: Short Date
		lineageTag: 3d2d2563-2edd-47c3-808f-15ff3d3e790d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 96fae878-6bb2-46ab-8495-842ff08d4f9f
			defaultHierarchy: LocalDateTable_52d8e505-a98d-4df7-9e7c-9e1a9c058c99.Datumshierarchie

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 257e9d81-27bf-4116-9a75-6f22950a6f7d
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 19105cce-f6a7-49bc-a350-ddcca4733c11
		summarizeBy: sum
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 709416a9-e41f-49fc-a652-e39db2925645
		summarizeBy: sum
		sourceColumn: Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: d7fecd40-c54c-469b-b23f-f7636731fe47
		isDefaultLabel
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuarterNo
		dataType: int64
		formatString: 0
		lineageTag: a56024fc-b2dc-475a-be6a-6b42c2114b3f
		summarizeBy: sum
		sourceColumn: QuarterNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Host Calendar Table' = m
		mode: import
		source =
				let
					// Set the start and end date for the date table
					StartDate = #date(2007, 01, 01),
					EndDate = #date(2025, 12, 31),
				 // Create a list of dates from the start to end date
					DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
					// Convert the list to a table and add columns for year, month, day, etc.
					DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
					#"Changed Type" = Table.TransformColumnTypes(DateTable,{{"Date", type date}}),
					#"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int32.Type),
					#"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), Int32.Type),
					#"Inserted Day" = Table.AddColumn(#"Inserted Month", "Day", each Date.Day([Date]), Int32.Type),
					#"Inserted MonthName" = Table.AddColumn(#"Inserted Day", "MonthName", each Date.ToText([Date], "MMMM"), type text),
					#"Inserted QuarterNo" = Table.AddColumn(#"Inserted MonthName", "QuarterNo", each Date.QuarterOfYear([Date]), Int32.Type)
				in
				    #"Inserted QuarterNo"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

